# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-notebook directory and image
# Set the workflow name
name: Test

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/base-notebook/ path
on:
  push:
    branches:
      - dev

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  test_job:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: gh-arc-ccpp-images
    # Set the steps to take in order
    steps:
      - run: |
            (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
            && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
            && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y