# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-notebook directory and image
# Set the workflow name
name: Test

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/base-notebook/ path
on:
  push:
    branches:
      - dev

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  test_job:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: gh-arc-ccpp-images
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Container Image
      - run: uname -a
      - run: apt-get install -y gh