name: Pull Request Workflow

on:
  pull_request_target:
    branches: [ "main" ]

jobs:

  run-on-self-hosted:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Run a script
      run: |
        echo "This script runs on the self-hosted runner!"
        echo "You can add your custom logic here."